/**
 * Oklahoma Agency–style State Agency Template (okagency).
 * Public landing: grants search (faceted search + results table). After login (password test): company match grants dashboard.
 */
export const okagencyTemplate = {
    id: 'okagency',
    name: 'State Agency',

    branding: {
        institutionName: 'Oklahoma Agency',
        tagline: 'Building businesses and communities.',
        logo: '/logo-okagency.svg',
    },

    header: {
        overlay: true,
        sticky: true,
        utilityIcons: ['search', 'globe', 'menu'],
        menuLabel: 'MENU',
    },

    content: {
        heroTitle: 'Building Businesses and Communities',
        heroSubtitle: 'Learn more about what makes Oklahoma the land of opportunity.',
        ctaText: 'Learn More',
        ctaSecondary: 'Sign Up for Newsletter',
        stateName: 'Oklahoma',
        stateAbbreviation: 'OK',
        welcomeMessage: 'Welcome to the State Agency Portal',
        blueBar: {
            newsletterText: 'Sign up for our Newsletter',
            scrollPromptText: 'Scroll to learn more',
            sidebarIcons: ['email', 'document'],
        },
        promoBar: {
            text: 'Click here for information on Oklahoma\'s Strategic Plan for Economic & Community Development',
            href: '#strategic-plan',
        },
        mainHeading: 'North America\'s Central Location for Business',
        mainTagline: 'A GLOBAL VISION WITH A LOCAL FOCUS',
        chatBubbleText: 'Can I help you find something?',
        chatAssistantTitle: 'Carey Grant Bot',
        chatAssistantSubtitle: 'Ask about Oklahoma grants, programs, and how to apply.',
        chatAssistantEmptyBody: 'Ask about state grant opportunities, eligibility, or deadlines.',
        chatAssistantEmptyTry: 'Tap * below for demo queries',
        chat: {
            samplePromptsByAgent: {
                'ok-grants-data': [
                    { label: 'Open workforce', prompt: 'What workforce grants are open right now?' },
                    { label: 'Closing soon', prompt: 'Which grants are closing soon?' },
                    { label: 'Infrastructure', prompt: 'Show infrastructure and broadband grants' },
                    { label: 'No match', prompt: "Which grants don't require a match?" },
                    { label: 'Small business', prompt: 'What grants can small businesses apply for?' },
                    { label: 'Catalog size', prompt: 'How many grants are in the catalog?' },
                    { label: 'Workforce vs business', prompt: 'Compare workforce training versus small-business awards and recommend a path for a rural manufacturer.', skipFastPath: true },
                    { label: 'Match tradeoff', prompt: 'How should a city decide between a match-required infrastructure award and a smaller no-match option?', skipFastPath: true },
                    { label: 'Commissioner brief', prompt: 'What would you brief a county commissioner on before applying for broadband funding?', skipFastPath: true },
                    { label: 'Missed cycle', prompt: 'Recommend next steps if our nonprofit missed last year\'s workforce cycle.', skipFastPath: true },
                    { label: 'Forecast vs open', prompt: 'Explain tradeoffs between forecasted and currently open economic development funding.', skipFastPath: true },
                    { label: 'Two-proposal cap', prompt: 'If staff can only write two proposals this quarter, how should they choose?', skipFastPath: true },
                ],
            },
        },
        grantsSearch: {
            pageTitle: 'Find grants',
            intro:
                'Search state grant opportunities. Use keywords and filters to narrow results. Live listings load from the grant index when available.',
            keywordLabel: 'Keyword search',
            keywordHint: 'Search titles and descriptions (e.g. workforce, broadband, small business).',
            keywordPlaceholder: 'What are you looking for?',
            refineHeading: 'Refine results',
            statusHeading: 'Show',
            statusForecasted: 'Forecasted',
            statusActive: 'Active',
            statusClosed: 'Closed',
            postAwardLabel: 'Post-award information only',
            postAwardHint: 'Limit to opportunities with post-award reporting details.',
            excludeLoansLabel: 'Do not show loan opportunities',
            excludeMatchLabel: 'Do not show opportunities requiring matched funding',
            filterAgencyLabel: 'Agency',
            filterCategoryLabel: 'Category',
            filterApplicantLabel: 'Eligible applicant',
            filterDisbursementLabel: 'Disbursement method',
            filterAny: 'Any',
            applyFilters: 'Apply filters',
            resetFilters: 'Reset',
            resultsHeading: 'Results',
            displayRange: 'Displaying {start} – {end} of {total}',
            perPageLabel: 'Per page',
            saveSearch: 'Save current search',
            applySaved: 'Apply saved search',
            clearSaved: 'Clear saved',
            savedToast: 'Search saved for your next visit.',
            clearedToast: 'Saved search removed.',
            glossaryLabel: 'Glossary',
            glossaryHref: '#glossary',
            faqLabel: 'FAQ',
            faqHref: '#faq',
            helpfulResources: 'Helpful resources',
            colDeadline: 'Deadline',
            colTitle: 'Grant title',
            colOpenDate: 'Open date',
            colAgency: 'Agency',
            colMatch: 'Match funding?',
            colEstimated: 'Est. total funding',
            colRange: 'Est. low / high',
            colDisbursement: 'Funds disbursement',
            statusLabelForecasted: 'Forecasted',
            statusLabelActive: 'Active',
            statusLabelClosed: 'Closed',
            prevPage: 'Previous',
            nextPage: 'Next',
            noResults: 'No grants match your criteria. Try adjusting filters or keywords.',
            loadingResults: 'Loading opportunities…',
            fallbackNotice:
                'Showing sample data because the grant index was unavailable or returned no rows.',
            grantDetailDescription: 'Description',
            grantDetailCategory: 'Category',
            grantDetailEligibleApplicant: 'Eligible applicant',
            grantDetailPostAward: 'Post-award reporting',
            grantDetailLoan: 'Loan opportunity',
            grantDetailMatchRequired: 'Matched funding required',
            grantDetailYes: 'Yes',
            grantDetailNo: 'No',
            grantTitleExpandHint: 'Click title to show or hide details',
        },
        dashboard: {
            pageTitle: 'Company Match Grants',
            pageSubtitle:
                'Monitor open applications, approved state match amounts, and reporting milestones for your organization.',
            heroHeading: 'Your company dashboard',
            alertBar:
                'Q2 match-grant round: letters of intent accepted through the date shown on your dashboard.',
            kpiOpenLabel: 'Open applications',
            kpiOpenValue: '2',
            kpiOpenHint: 'Awaiting agency review',
            kpiApprovedLabel: 'Approved state match (YTD)',
            kpiApprovedValue: '$325K',
            kpiApprovedHint: 'Paired with private match',
            kpiDisbursedLabel: 'Disbursed to date',
            kpiDisbursedValue: '$150K',
            kpiNextLabel: 'Next milestone',
            kpiNextValue: 'Apr 15',
            kpiNextHint: 'LOI deadline — Q2 round',
            tableTitle: 'Match grant applications',
            demoCompanyName: 'Red River Manufacturing LLC',
            statusLabelForecasted: 'Forecasted',
            statusLabelActive: 'Under review',
            statusLabelClosed: 'Closed – disbursed',
            newApplicationCta: 'Start new application',
            tableFootnote:
                'Sample data for demonstration. Amounts and statuses are illustrative; official records are maintained by the agency.',
            applicationsLoading: 'Loading applications…',
            tableFootnoteFromIndex:
                'Programs and dates are loaded from the state grant index. State match amounts use half of estimated total funding when available (illustrative split with private match).',
            deadlinesTitle: 'Upcoming deadlines',
            resourcesTitle: 'Program resources',
            resourcesBody:
                'Match ratios, eligible expenses, and compliance reporting differ by program. Always use the current published guidelines before applying.',
            resourcesCta: 'View guidelines',
        },
        staffDashboard: {
            pageTitle: 'Grant Program Dashboard',
            subtitle:
                'Match state grants to eligible businesses. Prioritize renewals, expiring award terms, and compliance follow-up.',
            priorityTableTitle: 'High-priority awards & renewals',
            colBusiness: 'Business / Award ID',
            colPriority: 'Priority',
            colLastActivity: 'Last portal activity',
            colAlert: 'Compliance / renewal',
            colFinancial: 'Match & disbursement',
            colAction: 'Action',
            tableDemoFootnote:
                'Demonstration data. Officer actions are illustrative; official records are maintained in the agency system of record.',
            kpiDisbursedLabel: 'State funds disbursed YTD',
            kpiDisbursedValue: '$18.4M',
            kpiRenewalLabel: 'Renewal & closeout package completion',
            kpiRenewalPercent: 72,
            kpiPipelineLabel: 'Applications in active pipeline',
            kpiPipelineValue: '842',
            docQueueTitle: 'Renewal & compliance document queue',
            deadlinesTitle: 'Approaching deadlines & expirations',
            calendarTitle: 'Program officer calendar',
            calendarToday: 'Today',
            atRiskTitle: 'Businesses — low portal activity',
            atRiskCaption: 'Days since last meaningful portal activity.',
            readMoreLink: 'Read more',
            expiringTitle: 'Grants & award terms expiring soon',
            matchedBusinessesLink: 'Matched businesses',
            pipelineTitle: 'Award pipeline status',
            pipelineSubmitted: 'Submitted',
            pipelineInReview: 'In review',
            pipelineAwarded: 'Awarded (active)',
            pipelineRenewal: 'Renewal due',
            pipelineClosed: 'Closed',
            pipelineFootnote: 'Counts are illustrative totals across all open programs.',
            primeTitle: 'Prime grant-match candidates',
            primeColBusiness: 'Business',
            primeColEligibility: 'Eligibility score',
            primeColEngagement: 'Last touch',
            primeColProfile: 'NAICS / size',
            actionEmail: 'Email',
            generateProgramEmailLabel: 'Email',
            actionCall: 'Call',
            actionSchedule: 'Schedule',
            actionRefer: 'Refer to program',
        },
        businessScorecard: {
            pageTitle: 'Business grant eligibility scorecard',
            back: 'Back',
            searchPlaceholder: 'Search business name or UEI…',
            searchButton: 'Search',
            viewingPrefix: 'Viewing business profile for',
            cardProfileTitle: 'Organization profile',
            cardFinancialTitle: 'Financial & grant alignment',
            cardActivityTitle: 'Engagement & compliance metrics',
            profileSubtitle: 'Industry | structure',
            entityIdLabel: 'UEI / Entity ID',
            phoneLabel: 'Phone',
            emailLabel: 'Email',
            locationLabel: 'Location',
            eligibilityGaugeLabel: 'Composite eligibility index',
            complianceBarLabel: 'Reporting & draw compliance',
            complianceTagOnTrack: 'On track',
            complianceTagWatch: 'Watch list',
            revenueBarLabel: 'Annual revenue (self-reported)',
            assetBarLabel: 'Asset band (program threshold)',
            readinessTitle: 'Grant readiness score',
            readinessSubtitleHigh: 'Strong match to open programs',
            readinessSubtitleMid: 'Moderate fit — documentation gaps',
            readinessSubtitleLow: 'Elevated risk — outreach recommended',
            matchEligibleLabel: 'Cost-share / match eligible',
            matchYes: 'Yes',
            matchNo: 'No',
            drawProgressLabel: 'Award draw-down progress',
            portalEngagementLabel: 'Portal engagement',
            documentSlaLabel: 'Document SLA adherence',
            trainingLabel: 'Required training / certifications',
            counterOpenFindings: 'Open compliance findings',
            counterPastDueTasks: 'Past-due tasks',
            counterOfficerMeetings: 'Officer touchpoints (90d)',
            costShareRatioLabel: 'Cost-share documentation ratio',
            demoFootnote:
                'Demonstration metrics for grant planning. Official eligibility determinations follow published program rules.',
        },
    },

    schemaLabels: {
        dashboardStaff: 'Grant Program Dashboard',
        staffRole: 'program staff',
    },

    colors: {
        primary: '#003366',
        secondary: '#2E7D32',
        accent: '#0ea5e9',
        slate: '#475569',
        charcoal: '#1e293b',
        warning: '#FF4F00',
        bgBase: '#0B0B0B',
        bgSurface: '#161616',
        white: '#ffffff',
        /** Semantic surfaces for shared okagency UI (see okagencyUi.js) */
        pageMuted: '#f8fafc',
        cardBorder: 'rgba(15, 23, 42, 0.08)',
    },

    typography: {
        fontFamily: '"Open Sans", "Montserrat", Inter, -apple-system, BlinkMacSystemFont, sans-serif',
        headingWeight: '700',
        headingTracking: '-0.02em',
    },

    navigation: {
        links: [
            { label: 'Business Services', href: '#business' },
            { label: 'Community Development', href: '#community' },
            { label: 'Strategic Plan', href: '#strategic-plan' },
            { label: 'Contact', href: '#contact' },
            { label: 'About', href: '#about' },
            { label: 'Resources', href: '#resources' },
        ],
    },

    hero: {
        backgroundImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1920&q=80',
        mainHeading: 'Building Businesses and Communities',
        subHeading: 'Learn more about what makes Oklahoma the land of opportunity.',
        overlayOpacity: 0.7,
        ctaButtons: {
            primary: 'Scroll to learn more',
            secondary: 'Sign up for our Newsletter',
        },
    },

    footer: {
        address: '123 State Capitol Boulevard, Oklahoma City, OK 73102',
        phone: '(555) 123-4567',
        quickLinks: [
            { label: 'Map', href: '#map' },
            { label: 'Employment', href: '#employment' },
            { label: 'Privacy', href: '#privacy' },
            { label: 'Accessibility', href: '#accessibility' },
        ],
        socialMedia: [
            { platform: 'FB', href: '#facebook', label: 'Facebook' },
            { platform: 'TW', href: '#twitter', label: 'Twitter' },
            { platform: 'IG', href: '#instagram', label: 'Instagram' },
            { platform: 'LI', href: '#linkedin', label: 'LinkedIn' },
        ],
    },

    schema: 'agency',

    elastic: {
        /**
         * Elastic Agent Builder agent ID on gawdzilla (must match Stack Management → Agent Builder).
         * Default id ok-grants-data — not the same string as the ES index ok-grant-data.
         * Uses OK_KIBANA_API_KEY. If your agent ID differs, change this and add the same id to
         * GAWDZILLA_AGENT_BUILDER_IDS in js/modules/utils/elasticApi.js plus nginx/vite agent chat routes.
         *
         * If chat returns 500: see env.template “Oklahoma Agency / Agent Builder” and the Network tab body.
         * Unset ELASTIC_AGENT_ID unless you intend to override this id globally.
         */
        agentId: 'ok-grants-data',
        /** Find Grants results: _search on gawdzilla (ok-fraud proxy + OK_KIBANA_API_KEY) */
        grantsDataIndex: 'ok-grant-data',
        grantsDataAgentId: 'ok-fraud',
        grantsSearchSize: 500,
        /** Company dashboard “Match grant applications” table: up to this many rows from the same index */
        dashboardGrantsMin: 2,
        dashboardGrantsMax: 5,
        workflows: {
            programEmail: {
                workflowId: 'ok-grant-program-officer-email',
                toolId: 'ok-grants-program-email-workflow',
            },
        },
    },

    search: {
        defaultFilters: { state: 'Oklahoma' },
        preferences: { sortBy: 'deadline', sortOrder: 'ASC' },
    },

    news: [
        {
            category: 'Economic Development',
            title: 'New Business Incentive Program Launches',
            description: 'State program offers grants and tax incentives to support small business growth and job creation.',
            image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&q=80',
        },
        {
            category: 'Community',
            title: 'Rural Communities Receive Infrastructure Grants',
            description: 'Funding will improve broadband access and local infrastructure in underserved areas.',
            image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80',
        },
        {
            category: 'Workforce',
            title: 'Workforce Development Initiative Expands',
            description: 'Partnership with local colleges will train workers for high-demand industries.',
            image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
        },
    ],

    grantsFilterOptions: {
        agencies: [
            { value: '', label: 'Any agency' },
            { value: 'commerce', label: 'Department of Commerce' },
            { value: 'transport', label: 'Department of Transportation' },
            { value: 'agriculture', label: 'Department of Agriculture' },
            { value: 'education', label: 'Department of Education' },
            { value: 'health', label: 'Department of Health' },
            { value: 'housing', label: 'Housing & Community Development' },
        ],
        categories: [
            { value: '', label: 'Any category' },
            { value: 'economic', label: 'Economic development' },
            { value: 'infrastructure', label: 'Infrastructure' },
            { value: 'education', label: 'Education' },
            { value: 'environment', label: 'Environment & water' },
            { value: 'health', label: 'Health & human services' },
            { value: 'workforce', label: 'Employment & training' },
        ],
        eligibleApplicants: [
            { value: '', label: 'Any applicant' },
            { value: 'business', label: 'Business' },
            { value: 'nonprofit', label: 'Nonprofit' },
            { value: 'public', label: 'Public agency' },
            { value: 'tribal', label: 'Tribal government' },
            { value: 'individual', label: 'Individual' },
        ],
        disbursementMethods: [
            { value: '', label: 'Any method' },
            { value: 'reimbursement', label: 'Reimbursement(s)' },
            { value: 'advance', label: 'Advance(s)' },
            { value: 'mixed', label: 'Advances & reimbursement(s)' },
        ],
    },

    /**
     * Demo catalog for grants search UI. Replace with API/Elasticsearch later if needed.
     * Fields align with StateAgencyGrantsSearch table and filter pipeline.
     */
    grantsCatalog: [
        { id: 'g1', title: 'Rural Broadband Expansion Fund', description: 'Fiber and fixed wireless for underserved communities.', status: 'active', postAwardInfo: true, isLoan: false, matchRequired: true, matchFunding: '25%', agency: 'commerce', category: 'infrastructure', eligibleApplicant: 'public', disbursementMethod: 'reimbursement', deadline: '2026-05-15', openDate: '2026-01-10', estimatedTotal: 12000000, rangeLowHigh: '$50K – $500K' },
        { id: 'g2', title: 'Small Business Innovation Voucher', description: 'Matched funding for R&D partnerships with local firms.', status: 'active', postAwardInfo: false, isLoan: false, matchRequired: true, matchFunding: '50%', agency: 'commerce', category: 'economic', eligibleApplicant: 'business', disbursementMethod: 'mixed', deadline: '2026-04-20', openDate: '2025-11-01', estimatedTotal: 3500000, rangeLowHigh: '$25K – $150K' },
        { id: 'g3', title: 'Main Street Revitalization Grant', description: 'Façade improvement and downtown placemaking.', status: 'forecasted', postAwardInfo: false, isLoan: false, matchRequired: false, matchFunding: 'No', agency: 'commerce', category: 'economic', eligibleApplicant: 'nonprofit', disbursementMethod: 'reimbursement', deadline: '2026-08-01', openDate: '2026-03-01', estimatedTotal: null, rangeLowHigh: 'Dependent' },
        { id: 'g4', title: 'Workforce Training Reimbursement', description: 'Tuition and certification for in-demand occupations.', status: 'active', postAwardInfo: true, isLoan: false, matchRequired: false, matchFunding: 'No', agency: 'education', category: 'workforce', eligibleApplicant: 'business', disbursementMethod: 'reimbursement', deadline: '2026-06-30', openDate: '2026-02-01', estimatedTotal: 8000000, rangeLowHigh: '$10K – $200K' },
        { id: 'g5', title: 'Clean Water Infrastructure Loan', description: 'Low-interest loan for municipal water systems.', status: 'active', postAwardInfo: false, isLoan: true, matchRequired: false, matchFunding: 'No', agency: 'health', category: 'environment', eligibleApplicant: 'public', disbursementMethod: 'advance', deadline: '2026-05-01', openDate: '2025-09-15', estimatedTotal: 25000000, rangeLowHigh: '$500K – $5M' },
        { id: 'g6', title: 'Agricultural Conservation Cost-Share', description: 'Soil health and water quality practices on working lands.', status: 'closed', postAwardInfo: true, isLoan: false, matchRequired: true, matchFunding: '75%', agency: 'agriculture', category: 'environment', eligibleApplicant: 'business', disbursementMethod: 'reimbursement', deadline: '2025-12-01', openDate: '2025-04-01', estimatedTotal: 4200000, rangeLowHigh: 'Dependent' },
        { id: 'g7', title: 'Community Health Clinic Expansion', description: 'Capital grants for rural clinic capacity.', status: 'active', postAwardInfo: true, isLoan: false, matchRequired: false, matchFunding: 'No', agency: 'health', category: 'health', eligibleApplicant: 'nonprofit', disbursementMethod: 'mixed', deadline: '2026-07-12', openDate: '2026-01-20', estimatedTotal: 15000000, rangeLowHigh: '$200K – $2M' },
        { id: 'g8', title: 'Transit Zero-Emission Fleet Pilot', description: 'Electric buses and charging for regional systems.', status: 'forecasted', postAwardInfo: false, isLoan: false, matchRequired: true, matchFunding: '20%', agency: 'transport', category: 'infrastructure', eligibleApplicant: 'public', disbursementMethod: 'advance', deadline: '2026-09-01', openDate: '2026-04-01', estimatedTotal: null, rangeLowHigh: '$1M – $8M' },
        { id: 'g9', title: 'Early Literacy Classroom Materials', description: 'Books and curriculum supports for Title I schools.', status: 'active', postAwardInfo: false, isLoan: false, matchRequired: false, matchFunding: 'No', agency: 'education', category: 'education', eligibleApplicant: 'public', disbursementMethod: 'reimbursement', deadline: '2026-04-05', openDate: '2026-01-05', estimatedTotal: 2200000, rangeLowHigh: '$5K – $75K' },
        { id: 'g10', title: 'Affordable Housing Tax Credit Bridge', description: 'Gap financing for qualified low-income housing.', status: 'active', postAwardInfo: true, isLoan: true, matchRequired: false, matchFunding: 'No', agency: 'housing', category: 'economic', eligibleApplicant: 'business', disbursementMethod: 'advance', deadline: '2026-05-22', openDate: '2025-10-01', estimatedTotal: 45000000, rangeLowHigh: 'Dependent' },
        { id: 'g11', title: 'Historic Preservation Matching Grant', description: 'Restore publicly significant structures.', status: 'closed', postAwardInfo: true, isLoan: false, matchRequired: true, matchFunding: '100%', agency: 'commerce', category: 'economic', eligibleApplicant: 'nonprofit', disbursementMethod: 'reimbursement', deadline: '2025-11-15', openDate: '2025-05-01', estimatedTotal: 900000, rangeLowHigh: '$25K – $250K' },
        { id: 'g12', title: 'STEM Teacher Stipend Program', description: 'Recruitment bonuses for high-need districts.', status: 'forecasted', postAwardInfo: false, isLoan: false, matchRequired: false, matchFunding: 'No', agency: 'education', category: 'education', eligibleApplicant: 'public', disbursementMethod: 'advance', deadline: '2026-10-01', openDate: '2026-06-01', estimatedTotal: null, rangeLowHigh: 'Dependent' },
        { id: 'g13', title: 'Wildfire Mitigation Community Fund', description: 'Defensible space and fuel reduction projects.', status: 'active', postAwardInfo: false, isLoan: false, matchRequired: false, matchFunding: 'No', agency: 'agriculture', category: 'environment', eligibleApplicant: 'public', disbursementMethod: 'reimbursement', deadline: '2026-03-30', openDate: '2025-12-01', estimatedTotal: 6000000, rangeLowHigh: '$50K – $400K' },
        { id: 'g14', title: 'Export Readiness Technical Assistance', description: 'Counseling for small businesses entering export markets.', status: 'active', postAwardInfo: true, isLoan: false, matchRequired: false, matchFunding: 'No', agency: 'commerce', category: 'economic', eligibleApplicant: 'business', disbursementMethod: 'reimbursement', deadline: '2026-08-15', openDate: '2026-02-15', estimatedTotal: 1800000, rangeLowHigh: '$5K – $40K' },
        { id: 'g15', title: 'County Bridge Safety Improvement', description: 'Structurally deficient bridge replacements.', status: 'active', postAwardInfo: true, isLoan: false, matchRequired: true, matchFunding: '10%', agency: 'transport', category: 'infrastructure', eligibleApplicant: 'public', disbursementMethod: 'mixed', deadline: '2026-12-01', openDate: '2025-08-01', estimatedTotal: 55000000, rangeLowHigh: '$500K – $12M' },
        { id: 'g16', title: 'Food Bank Cold Storage Upgrade', description: 'Refrigeration capacity for regional distributors.', status: 'closed', postAwardInfo: true, isLoan: false, matchRequired: false, matchFunding: 'No', agency: 'health', category: 'health', eligibleApplicant: 'nonprofit', disbursementMethod: 'reimbursement', deadline: '2025-09-30', openDate: '2025-03-01', estimatedTotal: 4000000, rangeLowHigh: '$75K – $500K' },
        { id: 'g17', title: 'Apprenticeship Expansion Incentive', description: 'Employer incentives for registered apprenticeship slots.', status: 'active', postAwardInfo: false, isLoan: false, matchRequired: true, matchFunding: '33%', agency: 'commerce', category: 'workforce', eligibleApplicant: 'business', disbursementMethod: 'reimbursement', deadline: '2026-06-01', openDate: '2026-01-01', estimatedTotal: 9500000, rangeLowHigh: 'Dependent' },
        { id: 'g18', title: 'Municipal Solar Feasibility Study', description: 'Planning grants for city-owned solar assessments.', status: 'forecasted', postAwardInfo: false, isLoan: false, matchRequired: false, matchFunding: 'No', agency: 'commerce', category: 'environment', eligibleApplicant: 'public', disbursementMethod: 'advance', deadline: '2026-11-01', openDate: '2026-05-01', estimatedTotal: null, rangeLowHigh: '$25K – $100K' },
        { id: 'g19', title: 'Tribal Broadband Planning Grant', description: 'Planning and engineering for tribal connectivity projects.', status: 'active', postAwardInfo: true, isLoan: false, matchRequired: false, matchFunding: 'No', agency: 'commerce', category: 'infrastructure', eligibleApplicant: 'tribal', disbursementMethod: 'mixed', deadline: '2026-04-28', openDate: '2025-12-10', estimatedTotal: 3200000, rangeLowHigh: '$100K – $400K' },
        { id: 'g20', title: 'Individual Artist Fellowship', description: 'Creative project grants for resident artists.', status: 'closed', postAwardInfo: false, isLoan: false, matchRequired: false, matchFunding: 'No', agency: 'commerce', category: 'economic', eligibleApplicant: 'individual', disbursementMethod: 'advance', deadline: '2025-10-01', openDate: '2025-04-15', estimatedTotal: 600000, rangeLowHigh: '$2K – $15K' },
        { id: 'g21', title: 'School Nutrition Equipment', description: 'Kitchen upgrades for K-12 meal programs.', status: 'active', postAwardInfo: false, isLoan: false, matchRequired: false, matchFunding: 'No', agency: 'education', category: 'education', eligibleApplicant: 'public', disbursementMethod: 'reimbursement', deadline: '2026-07-01', openDate: '2026-02-01', estimatedTotal: 5000000, rangeLowHigh: '$10K – $150K' },
        { id: 'g22', title: 'Regional Economic Recovery Loan', description: 'Working capital loan pool for disaster-impacted SMEs.', status: 'active', postAwardInfo: false, isLoan: true, matchRequired: false, matchFunding: 'No', agency: 'commerce', category: 'economic', eligibleApplicant: 'business', disbursementMethod: 'advance', deadline: '2026-09-15', openDate: '2025-07-01', estimatedTotal: 20000000, rangeLowHigh: 'Dependent' },
        { id: 'g23', title: 'Stream Restoration Partnership', description: 'Riparian buffer and habitat restoration.', status: 'forecasted', postAwardInfo: false, isLoan: false, matchRequired: true, matchFunding: '40%', agency: 'agriculture', category: 'environment', eligibleApplicant: 'nonprofit', disbursementMethod: 'reimbursement', deadline: '2027-01-15', openDate: '2026-07-01', estimatedTotal: null, rangeLowHigh: '$75K – $1M' },
        { id: 'g24', title: 'Public Library Digital Inclusion', description: 'Devices and hotspots for library patrons.', status: 'active', postAwardInfo: true, isLoan: false, matchRequired: false, matchFunding: 'No', agency: 'education', category: 'education', eligibleApplicant: 'public', disbursementMethod: 'reimbursement', deadline: '2026-05-30', openDate: '2026-01-25', estimatedTotal: 2800000, rangeLowHigh: '$15K – $120K' },
        { id: 'g25', title: 'Mobile Crisis Unit Equipment', description: 'Vehicles and telehealth kits for behavioral health response.', status: 'active', postAwardInfo: true, isLoan: false, matchRequired: true, matchFunding: '15%', agency: 'health', category: 'health', eligibleApplicant: 'public', disbursementMethod: 'mixed', deadline: '2026-08-30', openDate: '2026-03-10', estimatedTotal: 11000000, rangeLowHigh: '$250K – $1.5M' },
    ],

    login: {
        headline: 'Find grants, track programs, and grow Oklahoma businesses.',
        ssoButtonLabel: 'SSO through employer',
        features: [
            'Search active and forecasted state grant opportunities',
            'Filter by agency, category, and eligible applicant type',
            'Review deadlines, match requirements, and funding ranges',
            'Access program dashboards after authorized sign-in',
        ],
    },
};
